from __future__ import annotations

from typing import Any, Dict, List
from pydantic import BaseModel, Field
from llama_index.core.workflow import Event

# ============================================================
# Pydantic Schemas for Structured Agent Output Validation
# ============================================================

class SQLStructuredOutput(BaseModel):
    """Structured data returned by the SQL Specialist Agent for logical audit checks."""
    query: str = Field(..., description="A consulta SQL executada.")
    records: List[Dict[str, Any]] = Field(..., description="Os registros retornados do banco de dados.")
    uf: str = Field(..., description="A unidade federativa detectada.")
    setor: str = Field(..., description="O setor industrial detectada.")
    saldo_total: int = Field(..., description="O saldo total acumulado de empregos no período analisado.")
    tendencia: str = Field(..., description="Tendência dos dados: 'crescimento', 'queda' ou 'estavel'.")
    error_detail: str = Field("", description="Detalhes de erros ou falhas ocorridas durante a execução.")


class RAGStructuredOutput(BaseModel):
    """Structured insights extracted by the RAG Specialist Agent for cross-checking."""
    retrieved_passages: List[str] = Field(..., description="Trechos de relatórios recuperados.")
    setor_mencionado: str = Field(..., description="O setor industrial referenciado no relatório.")
    fator_macroeconomico: str = Field(..., description="Variável macro dominante identificada (ex: Selic alta, Câmbio, Inflação).")
    impacto_narrativa: str = Field(..., description="Qualificação qualitativa do impacto: 'positivo', 'negativo' ou 'neutro'.")
    error_detail: str = Field("", description="Detalhes de erros ou falhas ocorridas durante a execução.")


class ForecastStructuredOutput(BaseModel):
    """Structured projections generated by the Forecast Specialist Agent."""
    setor: str = Field(..., description="O setor industrial projetado.")
    horizonte_meses: int = Field(..., description="Horizonte da projeção em meses.")
    cenarios: Dict[str, Any] = Field(..., description="Projeções para os cenários base, otimista e pessimista.")
    tendencia_base: str = Field(..., description="Tendência estatística projetada no cenário base: 'crescimento', 'queda' ou 'estavel'.")
    modelo_utilizado: str = Field(..., description="Modelo econométrico ou de ML utilizado.")
    error_detail: str = Field("", description="Detalhes de erros ou falhas ocorridas durante a execução.")
    variaveis_macroeconomicas: Dict[str, Any] = Field(default_factory=dict, description="Variáveis macroeconômicas de contorno.")
    alertas: List[str] = Field(default_factory=list, description="Lista de alertas gerados.")


class AuditorVerdict(BaseModel):
    """Quality control decision from the Consistency Auditor Agent."""
    approved: bool = Field(..., description="Se o relatório foi aprovado pelo controle de consistência.")
    feedback: str = Field("", description="Detalhes e instruções de refatoração em caso de reprovação.")
    report: str = Field("", description="O relatório econômico final refinado em Markdown se aprovado.")


# ============================================================
# LlamaIndex Workflow Custom Events
# ============================================================

class SQLQueryEvent(Event):
    """Event triggered by Orchestrator requesting SQL database query execution."""
    query: str
    revisor_feedback: str = ""


class RAGRetrievalEvent(Event):
    """Event triggered by Orchestrator requesting qualitative context search (RAG)."""
    query: str


class ForecastEvent(Event):
    """Event triggered by Orchestrator requesting time-series forecasting."""
    setor: str
    horizonte_meses: int
    revisor_feedback: str = ""


class SQLResultEvent(Event):
    """Contains the structured query output from the SQL Specialist."""
    data: SQLStructuredOutput


class RAGResultEvent(Event):
    """Contains the qualitative semantic output from the RAG Specialist."""
    data: RAGStructuredOutput


class ForecastResultEvent(Event):
    """Contains the statistical forecast data from the Forecast Specialist."""
    data: ForecastStructuredOutput


class AuditorEvaluationEvent(Event):
    """Verdict of the Auditor (Approved or Rejected)."""
    verdict: AuditorVerdict


class OrchestratorThoughtEvent(Event):
    """Event triggered to stream Orchestrator progress, tasks, or final state to the UI."""
    message: str
    subtasks: List[str] = []


class AgentThoughtEvent(Event):
    """Event triggered by any specialist agent to log its thinking, actions, and outputs to the UI."""
    agent: str
    thought: str
    action: str
    output: str


class ConclusionEvent(Event):
    """Event triggered when ConsistencyAuditor approves the report."""
    report: str
    sql_data: SQLStructuredOutput
    rag_data: RAGStructuredOutput
    forecast_data: ForecastStructuredOutput
    verdict: AuditorVerdict

