"""
Industrial Multi-Agent Ecosystem — Analysis Agent (Agente 2).

Responsible for detecting statistical anomalies (e.g. sharp payroll drops, acute layoff waves)
in ingested industrial data using Z-score and Interquartile Range (IQR) algorithms.
"""

from __future__ import annotations

import logging
import time
from typing import Any
import numpy as np
import pandas as pd
from pydantic import BaseModel, Field

from config import get_settings
from core.metrics import AGENT_EXECUTION_DURATION, ANOMALIES_DETECTED
from agents.ingestion_agent import IngestionSummary

logger = logging.getLogger(__name__)


class AnomalyDetail(BaseModel):
    """Schema representing an individual detected statistical anomaly."""

    uf: str = Field(..., description="Brazilian state code")
    setor: str = Field(..., description="Industrial sector")
    mes_ano: str = Field(..., description="Period (YYYY-MM)")
    metric_name: str = Field(..., description="Metric exhibiting anomaly (massa_salarial or saldo)")
    observed_value: float = Field(..., description="Observed value in the anomaly period")
    baseline_mean: float = Field(..., description="Baseline mean for this sector/UF group")
    z_score: float = Field(..., description="Calculated Z-score statistic")
    percentage_change: float = Field(..., description="Percentage variation relative to baseline mean")
    severity: str = Field(..., description="Severity classification (CRITICAL, HIGH, MEDIUM)")
    description: str = Field(..., description="Human-readable explanation of anomaly")


class AnalysisSummary(BaseModel):
    """Structured output payload generated by the Analysis Agent."""

    total_records_analyzed: int = Field(..., description="Total rows analyzed")
    anomalies_found_count: int = Field(..., description="Total statistical anomalies identified")
    anomalies: list[AnomalyDetail] = Field(default_factory=list, description="List of detected anomalies")
    critical_count: int = Field(0, description="Count of critical severity anomalies")
    execution_time_ms: float = Field(..., description="Execution duration in milliseconds")


class AnalysisAgent:
    """
    Analysis Agent: Detects statistical anomalies in industrial employment data
    using Z-Score and IQR algorithms across sector and state groupings.
    """

    @classmethod
    def run(
        cls,
        ingestion_data: IngestionSummary | list[dict[str, Any]],
        z_threshold: float | None = None,
    ) -> AnalysisSummary:
        """
        Detect statistical anomalies across sector & UF groups.
        """
        start_time = time.perf_counter()
        settings = get_settings()
        if z_threshold is None:
            z_threshold = settings.anomaly_zscore_threshold

        logger.info(
            "AnalysisAgent starting anomaly detection",
            extra={
                "event_type": "agent_decision",
                "agent": "AnalysisAgent",
                "action": "STATISTICAL_ANALYSIS_START",
                "z_threshold": z_threshold,
            },
        )

        records = (
            ingestion_data.records
            if isinstance(ingestion_data, IngestionSummary)
            else ingestion_data
        )

        df = pd.DataFrame(records)
        if df.empty:
            return AnalysisSummary(
                total_records_analyzed=0,
                anomalies_found_count=0,
                anomalies=[],
                critical_count=0,
                execution_time_ms=0.0,
            )

        anomalies: list[AnomalyDetail] = []
        critical_count = 0

        # Group by UF and Setor to establish localized statistical baselines
        groups = df.groupby(["uf", "setor"])

        for (uf, setor), group in groups:
            if len(group) < 3:
                continue

            for metric in ["massa_salarial", "saldo"]:
                values = group[metric].to_numpy(dtype=float)
                mean = float(np.mean(values))
                std = float(np.std(values))

                if std == 0:
                    continue

                for idx, row in group.iterrows():
                    val = float(row[metric])
                    z_score = round((val - mean) / std, 2)

                    # We are looking for negative drops (Z < -threshold) or positive spikes in layoffs
                    if abs(z_score) >= z_threshold:
                        pct_change = round(((val - mean) / abs(mean)) * 100, 2) if mean != 0 else 0.0

                        if abs(z_score) >= 3.0 or pct_change <= -40.0:
                            severity = "CRITICAL"
                            critical_count += 1
                        elif abs(z_score) >= 2.5 or pct_change <= -25.0:
                            severity = "HIGH"
                        else:
                            severity = "MEDIUM"

                        desc = (
                            f"Anomalia estatística em {setor} ({uf}) em {row['mes_ano']}: "
                            f"{metric} de {val:,.2f} representa variação de {pct_change}% "
                            f"(Z-score: {z_score}, Média histórica: {mean:,.2f})."
                        )

                        anomaly = AnomalyDetail(
                            uf=str(uf),
                            setor=str(setor),
                            mes_ano=str(row["mes_ano"]),
                            metric_name=metric,
                            observed_value=val,
                            baseline_mean=round(mean, 2),
                            z_score=z_score,
                            percentage_change=pct_change,
                            severity=severity,
                            description=desc,
                        )
                        anomalies.append(anomaly)

                        # Update Prometheus anomaly counter
                        ANOMALIES_DETECTED.labels(sector=str(setor), severity=severity).inc()

        exec_duration_s = time.perf_counter() - start_time
        exec_duration_ms = round(exec_duration_s * 1000, 2)

        AGENT_EXECUTION_DURATION.labels(agent="AnalysisAgent").observe(exec_duration_s)

        logger.info(
            "AnalysisAgent completed anomaly detection",
            extra={
                "event_type": "agent_decision",
                "agent": "AnalysisAgent",
                "action": "STATISTICAL_ANALYSIS_COMPLETE",
                "total_records": len(df),
                "anomalies_found": len(anomalies),
                "critical_count": critical_count,
                "execution_time_ms": exec_duration_ms,
            },
        )

        return AnalysisSummary(
            total_records_analyzed=len(df),
            anomalies_found_count=len(anomalies),
            anomalies=anomalies,
            critical_count=critical_count,
            execution_time_ms=exec_duration_ms,
        )
